apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: {{ .Values.redis_stack_server.service.port }}
    name: {{ .Values.name }}
  type: {{ .Values.redis_stack_server.service.type }}
  selector:
    app: "{{ .Values.name }}"

