apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: 6379
    name: redis-stack
    targetPort: 6379
  type: NodePort
  selector:
    app: redis-stack
